{{- if has "adminapp" .Values.global.modules }}
---
apiVersion: "microgateway.airlock.com/v1alpha1"
kind: "DenyRules"
metadata:
  name: "adminapp-rest-deny-rules"
spec:
  request:
    builtIn:
      settings:
        level: "Strict"
        threatHandlingMode: "Block"
      exceptions:
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "SQL"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^sso$"
                ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^filter$"
                ignoreCase: false
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.adminapp }}/rest/logs/.*$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^(loginUrl|afterLogoutUrl)$"
                ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            jsonPath: "$.loginUrl"
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            jsonPath: "$.afterLogoutUrl"
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^Location$"
                ignoreCase: false
            value:
              matcher:
                regex: "^editConfig.*"
                ignoreCase: false
      - ruleKeys:
        - "TEMPLATE"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "HTML"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "HTML"
        blockedData:
          json:
            jsonPath: "$.data.attributes.translations.en"
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.adminapp }}/rest/maintenance-messages.*"
              ignoreCase: false
      - ruleKeys:
        - "HTML"
        blockedData:
          json:
            jsonPath: "$.data.attributes.translations.fr"
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.adminapp }}/rest/maintenance-messages.*"
              ignoreCase: false
      - ruleKeys:
        - "HTML"
        blockedData:
          json:
            jsonPath: "$.data.attributes.translations.de"
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.adminapp }}/rest/maintenance-messages.*"
              ignoreCase: false
      - ruleKeys:
        - "HTML"
        blockedData:
          json:
            jsonPath: "$.data.attributes.translations.it"
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.adminapp }}/rest/maintenance-messages.*"
              ignoreCase: false
      - ruleKeys:
        - "UNIXCMD"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "WINCMD"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "LDAP"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "PHP"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "OGNL"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "IDOR"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^sso$"
                ignoreCase: false
      - ruleKeys:
        - "NOSQL"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "SANITY"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "ENCODING"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "PROTOCOL"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "HPP"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "HPP"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^Location$"
                ignoreCase: false
            value:
              matcher:
                regex: "^editConfig.*"
                ignoreCase: false
      - ruleKeys:
        - "EXPLOIT"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"
      - ruleKeys:
        - "SCANNING"
        blockedData:
          json:
            jsonPath: "$['password','oldPassword','newPassword']"

{{- end }}