{{- if has "transaction-approval" .Values.global.modules }}
---
apiVersion: "microgateway.airlock.com/v1alpha1"
kind: "DenyRules"
metadata:
  name: "transaction-approval-deny-rules"
spec:
  request:
    builtIn:
      settings:
        level: "Strict"
        threatHandlingMode: "Block"
      exceptions:
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^filter$"
                ignoreCase: false

{{- end }}