{{- if has "loginapp" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: HeaderRewrites
metadata:
  name: iam-loginapp-header-rewrites
spec:
  request:
    allow:
      matchingHeaders:
        custom:
          - headers:
              - name:
                  matcher:
                    exact: "X-Captcha-Solution"
            name: "CAPTCHA solution Header"
          - headers:
              - name:
                  matcher:
                    exact: "X-Continue-Flow"
            name: "Continue flow header"
          - headers:
              - name:
                  matcher:
                    exact: "X-Flow-Continuation-Token"
            name: "Flow continuation header"
          - headers:
              - name:
                  matcher:
                    exact: "X-Iam-Sso-Ticket"
            name: "SSO Ticket header"
  response:
    remove:
      builtIn:
        auth:
          negotiate: false

{{- end }}