{{- if has "loginapp" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: APIProtection
metadata:
  name: iam-loginapp-rest-protected-api-protection
spec:
  policies:
  - name: Loginapp Protected REST API
    openAPIRef:
      name: loginapp-protected-openapi

{{- end }}