apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.secretName }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  {{- if .Values.certificate.commonName }}
  commonName: {{ quote .Values.certificate.commonName }}
  {{- end }}
  dnsNames: {{ .Values.certificate.dnsNames | toYaml | nindent 4 }}
  issuerRef:
    kind: Issuer
    name: {{ .Values.certificate.issuerName  }}
