{{- if has "adminapp" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurity
metadata:
  name: adminapp-config-editor-content-security
spec:
  parserRef:
    name: iam-parser
  limitsRef:
    name: iam-limits
  headerRewritesRef:
    name: iam-adminapp-config-editor-header-rewrites
  filter:
    denyRulesRef:
      name: iam-adminapp-config-editor-deny-rules

{{- end }}