{{- if has "loginapp" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurity
metadata:
  name: loginapp-content-security
spec:
  parserRef:
    name: iam-parser
  limitsRef:
    name: iam-limits
  filter:
    denyRulesRef:
      name: loginapp-deny-rules
  headerRewritesRef:
    name: iam-loginapp-header-rewrites

{{- end }}