{{- if has "adminapp" .Values.global.modules }}
{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurityPolicy
metadata:
  name: adminapp-rest-content-security-policy
spec:
  targetRefs:
    - name: backend-adminapp-rest
      kind: HTTPRoute
      group: gateway.networking.k8s.io
  secured:
    parserRef:
      name: iam-parser
    limitsRef:
      name: iam-limits
    filter:
      denyRulesRef:
        name: adminapp-rest-deny-rules
    apiProtectionRef:
      name: iam-adminapp-rest-api-protection
    headerRewritesRef:
      name: iam-adminapp-rest-header-rewrites
{{- end }}

{{- end }}