{{- if has "loginapp" .Values.global.modules }}
{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurityPolicy
metadata:
  name: loginapp-rest-public-content-security-policy
spec:
  targetRefs:
    - name: backend-loginapp-rest-public
      kind: HTTPRoute
      group: gateway.networking.k8s.io
  secured:
    parserRef:
      name: iam-parser
    limitsRef:
      name: iam-limits
    filter:
      denyRulesRef:
        name: loginapp-rest-public-deny-rules
    headerRewritesRef:
      name: iam-loginapp-rest-public-header-rewrites
    apiProtectionRef:
      name: iam-loginapp-rest-public-api-protection
{{- end }}

{{- end }}