{{- if has "transaction-approval" .Values.global.modules }}
{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurityPolicy
metadata:
  name: transaction-approval-rest-content-security-policy
spec:
  targetRefs:
    - name: backend-transaction-approval-rest
      kind: HTTPRoute
      group: gateway.networking.k8s.io
  secured:
    parserRef:
      name: iam-parser
    limitsRef:
      name: iam-limits
    filter:
      denyRulesRef:
        name: transaction-approval-deny-rules
    apiProtectionRef:
      name: iam-transaction-approval-rest-api-protection
    headerRewritesRef:
      name: iam-transaction-approval-header-rewrites
{{- end }}

{{- end }}