{{- if has "loginapp" .Values.global.modules }}
{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurityPolicy
metadata:
  name: loginapp-content-security-policy
spec:
  targetRefs:
    - name: backend-loginapp
      kind: HTTPRoute
      group: gateway.networking.k8s.io
  secured:
    parserRef:
      name: iam-parser
    limitsRef:
      name: iam-limits
    filter:
      denyRulesRef:
        name: loginapp-deny-rules
    headerRewritesRef:
      name: iam-loginapp-header-rewrites
{{- end }}

{{- end }}