{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: iam-backend-tls-policy
spec:
  targetRefs:
    - name: {{ quote .Values.gatewayApi.targetService.name }}
      kind: Service
      group: ""
      sectionName: {{ quote .Values.gatewayApi.targetService.sectionName }}
  validation:
    hostname: {{ .Values.gatewayApi.targetService.hostname }}
    {{- if .Values.gatewayApi.targetService.wellKnownCACertificates }}
    wellKnownCACertificates: {{ .Values.gatewayApi.targetService.wellKnownCACertificates }}
    {{- end }}
    {{- if .Values.gatewayApi.targetService.caCertificateRefs }}
    caCertificateRefs:
{{ toYaml .Values.gatewayApi.targetService.caCertificateRefs | indent 6 }}
    {{- end }}
  options:
{{ toYaml .Values.gatewayApi.targetService.tlsOptions | indent 4 }}
{{- end }}
