{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ quote .Values.gatewayApi.engine.name }}
spec:
  gatewayClassName: {{ quote .Values.gatewayApi.gatewayClassName }}
  infrastructure:
    parametersRef:
      name: "{{ .Values.gatewayApi.engine.name }}-parameters"
      kind: GatewayParameters
      group: microgateway.airlock.com
  listeners:
    - name: https
      {{- if .Values.gatewayApi.engine.hostname }}
      hostname: {{ quote .Values.gatewayApi.engine.hostname }}
      {{- end }}
      protocol: HTTPS
      port: {{ .Values.gatewayApi.engine.httpsPort }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.certificate.secretName }}
        options:
{{ toYaml .Values.gatewayApi.engine.tlsOptions | indent 10 }}
{{- end }}
