{{- if has "adminapp" .Values.global.modules }}
{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-adminapp-rest
spec:
  parentRefs:
    - name: {{ quote .Values.gatewayApi.engine.name }}
      kind: Gateway
      group: gateway.networking.k8s.io
      sectionName: https
  rules:
    - matches:
        - path:
            value: {{ .Values.global.path.adminapp }}/rest
      backendRefs:
        - name: {{ .Values.gatewayApi.targetService.name }}
          kind: Service
          group: ""
          port: {{ .Values.gatewayApi.targetService.port }}
{{- end }}

{{- end }}