{{- if has "adminapp" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurity
metadata:
  name: adminapp-content-security
spec:
  parserRef:
    name: iam-parser
  limitsRef:
    name: iam-limits
  filter:
    denyRulesRef:
      name: adminapp-deny-rules

{{- end }}