{{- if has "loginapp" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurity
metadata:
  name: loginapp-rest-protected-content-security
spec:
  parserRef:
    name: iam-parser
  limitsRef:
    name: iam-limits
  filter:
    denyRulesRef:
      name: loginapp-rest-protected-deny-rules
  headerRewritesRef:
    name: iam-loginapp-rest-protected-header-rewrites
  apiProtection:
    openAPIRef:
      name: loginapp-openapi

{{- end }}