{{- if has "service-container" .Values.global.modules }}
---
apiVersion: "microgateway.airlock.com/v1alpha1"
kind: "DenyRules"
metadata:
  name: "servicecontainer-deny-rules"
spec:
  request:
    builtIn:
      settings:
        level: "Standard"
        threatHandlingMode: "Block"
      exceptions: []

{{- end }}