{{- if has "service-container" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: DenyRules
metadata:
  name: servicecontainer-deny-rules
spec:
  request:
    builtIn:
      settings:
        level: Strict
        threatHandlingMode: Block
# SSRF deny rule introduced in Microgateway 4.4
{{- if semverCompare ">=4.4" .Values.global.microgatewayVersion }}
      overrides:
        - conditions:
            ruleKeys:
              - SSRF
            types:
              - JSON
          settings:
            level: Unfiltered
{{- end }}
      exceptions:
      - ruleKeys:
        - "SQL"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.serviceContainer }}/serviceContainer$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.serviceContainer }}/serviceContainer$"
              ignoreCase: false
      - ruleKeys:
        - "HPP"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.serviceContainer }}/serviceContainer$"
              ignoreCase: false
{{- if semverCompare ">=4.4" .Values.global.microgatewayVersion }}
      - ruleKeys:
        - "SSRF"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          path:
            matcher:
              regex: "^{{ .Values.global.path.serviceContainer }}/serviceContainer$"
              ignoreCase: false
{{- end }}

{{- end }}