{{- if has "service-container" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: HeaderRewrites
metadata:
  name: iam-servicecontainer-header-rewrites
spec:
  response:
    add:
      builtIn:
        csp: false

{{- end }}