{{- if has "loginapp" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: OpenAPI
metadata:
  name: loginapp-openapi
spec:
  settings:
    schema:
      source:
        configMapRef:
          name: loginapp-openapi-configmap
    threatHandlingMode: Block
  response:
    secured: { }

{{- end }}