{{- if not .Values.global.microgatewaySidecarMode }}
{{- if .Values.gatewayApi.unsecuredPaths }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: ContentSecurityPolicy
metadata:
  name: unsecured-content-security-policy
spec:
  targetRefs:
{{- range .Values.gatewayApi.unsecuredPaths }}
  - name: {{ .name }}
    kind: HTTPRoute
    group: gateway.networking.k8s.io
{{- end }}
  unsecured: {}
{{- end }}
{{- end }}
