{{- if not .Values.global.microgatewaySidecarMode }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: iam-gateway-envoy-extension-policy
spec:
  targetRefs:
    {{- if has "adminapp" .Values.global.modules }}
  - name: backend-adminapp
    kind: HTTPRoute
    group: gateway.networking.k8s.io
  - name: backend-adminapp-rest
    kind: HTTPRoute
    group: gateway.networking.k8s.io
  - name: backend-config-editor
    kind: HTTPRoute
    group: gateway.networking.k8s.io
    {{- end }}
    {{- if has "loginapp" .Values.global.modules }}
  - name: backend-loginapp
    kind: HTTPRoute
    group: gateway.networking.k8s.io
  - name: backend-loginapp-rest-oauth2
    kind: HTTPRoute
    group: gateway.networking.k8s.io
  - name: backend-loginapp-rest-protected
    kind: HTTPRoute
    group: gateway.networking.k8s.io
  - name: backend-loginapp-rest-public
    kind: HTTPRoute
    group: gateway.networking.k8s.io
    {{- end }}
    {{- if has "service-container" .Values.global.modules }}
  - name: backend-service-container
    kind: HTTPRoute
    group: gateway.networking.k8s.io
    {{- end }}
    {{- if has "transaction-approval" .Values.global.modules }}
  - name: backend-transaction-approval-rest
    kind: HTTPRoute
    group: gateway.networking.k8s.io
    {{- end }}
  - name: backend-unspecified-path
    kind: HTTPRoute
    group: gateway.networking.k8s.io
  envoyHTTPFilterRefs:
    prepend:
    - name: iam-http-filter-secure-cookie-rewrite
{{- end }}
